controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    ackermann_drive_base_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_drive_base_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: false   # Use true to make controller topic /ackermann_steering_controller/reference listen to TwistStamped type data
                            # Use false ro make controller topic /ackermann_steering_controller/reference_unstamped listen to Twist type data
    rear_wheels_names: [base_back_r_wheel_joint, base_back_l_wheel_joint]
    front_wheels_names: [base_r_steer_joint, base_l_steer_joint]

    wheelbase: 0.4               # Distance between front and rear wheel axes
    front_wheel_track: 0.4      # Distance between front wheels
    rear_wheel_track: 0.4       # Distance between rear wheels
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1
